### ISSUE TITLE
Indicator on wrong answer

### ISSUE THREAD

**Issue by matthewglover** [smooth-operators-fac/BradleyJakubStopwatch#8]
When you click on wrong answer nothing happens. Maybe it would be a good idea to have some colour change on clicking a wrong answer as well as not moving to next question.

Also, perhaps you could change the cursor to a hand to indicate that these are buttons you can press.

**Comment by JakubSvihla** [comment]
added a cursor pointer to the clickable divs and the background-color changes when wrong answer is clicked
